# Generated by Django 3.0.5 on 2020-05-01 16:08

from django.db import migrations, models
import pasal.models


class Migration(migrations.Migration):

    dependencies = [
        ('pasal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pasal.models.upload_path),
        ),
    ]
