# Generated by Django 3.0.5 on 2020-05-01 16:15

from django.db import migrations, models
import pasal.models


class Migration(migrations.Migration):

    dependencies = [
        ('pasal', '0002_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default=1, upload_to=pasal.models.upload_path),
            preserve_default=False,
        ),
    ]
